### PR TITLE
Fixed autolayout on login and launch screen.

### PR DESCRIPTION
**Pull request by kieranwoodrow**

### CODE REVIEW

**Review by KirstyPallatte — COMMENTED** [review]
Looking good.

**Review by smabhena — DISMISSED** [review]
👍

**Review by bgouws — DISMISSED** [review]
Would be nice to see some screenshots in the description.

**Review by bgouws — APPROVED** [review]

**Review by KirstyPallatte — APPROVED** [review]
Looking good!

**Review by smabhena — APPROVED** [review]
Looks good to me👍

**Pull request merged**
